id: ViT
seed: 2104
pretrained_path: trained/pre-trained/ViT-B_16.npz
model:
    img_size: 224
    patch_size: 16
    n_classes: 100
    dim: 768
    n_head: 12
    n_layer: 12
    mlp_dim: 3072
    drop_rate: 0.1
    attn_drop_rate: 0.0
    is_visualize: False
    hybrid:
        n_layer: 0 #[3, 4, 9]
        width_factor: 0 #1
trainer:
    nepochs: 100
    val_step: 1
    log_step: 30
    lr: !!float 1e-4
    weight_decay: !!float 0.1
optimizer:
    adam_eps: !!float 1e-8
    patience: 5
    warmup: 10
    clip: 1.0    
    factor: 0.5
dataset:
    name: CIFARDataset
    root_dir: data/
    train:
        batch_size: 8
        shuffle: True
        clip_grads: True
    val:
        batch_size: 5
