id: ViT
seed: 2104
pretrained_path: trained/ViT-DogCatDataset-lr:0.0001-2021_05_19-10_02_23-with_bias
model_filename: best_acc-val_acc=0.769.pth
model:
    img_size: 224
    patch_size: 16
    n_classes: 2
    dim: 512
    n_head: 8
    n_layer: 6
    mlp_dim: 1024
    is_visualize: True
dataset:
    root_dir: data/dogcat/
    val:
        batch_size: 1
        shuffle: False
        num_workers: 8
result:
    root_dir: attn_results/