id: ViT
seed: 2104
pretrained_path: checkpoints/ViT-2021_05_11-11_32_05
model_filename: best_bleu-val_acc=0.61.pth
model:
    img_size: 32
    patch_size: 4
    n_classes: 10
    dim: 64
    n_head: 8
    n_layer: 6
    mlp_dim: 128
    is_visualize: True
dataset:
    root_dir: data/cifar10/images
    test:
        k: 5